# Generated by Django 2.2.14 on 2021-04-24 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('puntuacion', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaEsquema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('IN', 'Informativa'), ('DG', 'DIGEFE'), ('EX', 'Extranormativa')], max_length=2)),
                ('esquema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AuditoriaEsquema')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.TextField(max_length=50, unique=True)),
                ('esta_habilitado', models.BooleanField(default=False)),
                ('ciudad', models.TextField(max_length=40)),
                ('coord_lat', models.FloatField(null=True)),
                ('coord_ing', models.FloatField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=60)),
                ('apellido', models.TextField(max_length=60)),
                ('fecha_de_nacimiento', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('esta_habilitado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('JR', 'Junior'), ('MID', 'Mid-level'), ('SR', 'Senior')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('validez', models.CharField(choices=[('JR', 'Junior'), ('MID', 'Mid-level'), ('SR', 'Senior')], max_length=3)),
                ('auditoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Auditoria')),
                ('pregunta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('JR', 'Junior'), ('MID', 'Mid-level'), ('SR', 'Senior')], max_length=3)),
                ('respuesta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Respuesta')),
            ],
        ),
        migrations.AddField(
            model_name='auditoria',
            name='esquema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AuditoriaEsquema'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='sucursal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sucursal'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
    ]
