# Generated by Django 2.2.14 on 2021-06-11 03:17

from django.db import migrations, models
import server.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=server.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
