# Generated by Django 2.2.14 on 2021-05-31 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='respuesta_ok',
            new_name='respuesta_correcta',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='bardrio',
            new_name='barrio',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='numero',
            new_name='numero_de_sag',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='puntuacion',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='usuario',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='reporta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='tipo',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Image', 'Image')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('Informativa', 'Informativa'), ('DIGEFE', 'DIGEFE'), ('Extranormativa', 'Extranormativa')], max_length=14),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='seccion',
            field=models.CharField(choices=[('Afuera', 'Afuera'), ('Adentro', 'Adentro'), ('Caja', 'Caja')], default='Afuera', max_length=7),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Numerica', 'Numerica'), ('Opciones', 'Opciones')], default='Audio', max_length=8),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='coord_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='coord_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
