# Generated by Django 2.2.14 on 2021-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210531_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
