# Generated by Django 2.2.14 on 2021-06-21 03:28

from django.db import migrations, models
import server.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210621_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=server.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
