# Generated by Django 2.2.14 on 2021-06-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_respuesta_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='audio',
        ),
    ]
