# Generated by Django 2.2.14 on 2021-06-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_respuesta_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='path_imagen_url',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
