# Generated by Django 2.2.14 on 2021-04-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210424_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='esquema',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='esquema_id',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AuditoriaEsquema',
        ),
    ]
