# Generated by Django 2.2.14 on 2021-06-05 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sucursal_ultimo_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='ultimo_responsable',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultima_sucursal', to=settings.AUTH_USER_MODEL),
        ),
    ]
