# Generated by Django 2.2.14 on 2021-06-13 23:29

from django.db import migrations, models
import server.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sucursal_path_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='path_imagen_url',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='audio',
            field=models.ImageField(blank=True, null=True, storage=server.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
