# Generated by Django 2.2.14 on 2021-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210425_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='sucursal_id',
            new_name='sucursal',
        ),
        migrations.RenameField(
            model_name='auditoria',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='respuesta_id',
            new_name='respuesta',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='auditoria_id',
            new_name='auditoria',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='pregunta_id',
            new_name='pregunta',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='audio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
