# Generated by Django 2.2.14 on 2021-04-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210425_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='audio',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
