# Generated by Django 2.2.14 on 2021-06-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210613_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='audio',
            new_name='imagen',
        ),
    ]
