# Generated by Django 2.2.14 on 2021-06-13 23:36

from django.db import migrations, models
import server.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210613_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=server.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
