# Generated by Django 2.2.14 on 2021-04-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210425_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='usuario',
        ),
    ]
