# Generated by Django 2.2.14 on 2021-04-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210425_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('audi', 'Audio'), ('nume', 'Numerica'), ('opci', 'Opciones')], default='audi', max_length=4),
        ),
    ]
