# Generated by Django 2.2.14 on 2021-04-26 02:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pregunta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='opciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
    ]
