# Generated by Django 2.2.14 on 2021-04-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210427_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='texto',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='notas',
            field=models.TextField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios_de_respuesta/'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='validez',
            field=models.BooleanField(default=False),
        ),
    ]
