# Generated by Django 2.2.14 on 2021-04-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210427_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='notas',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
