version: '3'
services:
    app:
        build: .
        container_name: speech-to-text-server
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - ./:/code
        ports:
            - 8000:80
        depends_on:
            - db
        environment:
            - DEBUG=True
            - DATABSE_NAME=app
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
            - DATABASE_USER=ingdesw
            - DATABASE_PASSWORD=password
    db:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=ingdesw
            - POSTGRES_PASSWORD=password