version: '4'
services:
  app:
    build: .
    container_name: speech-to-text-server
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./:/code
    ports:
      - 8000:80
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=ingdesw
      - POSTGRES_PASSWORD=password

volumes:
      postgres_data: