export const FETCH_PREGUNTAS_REQUEST = 'FETCH_PREGUNTAS_REQUEST';
export const FETCH_PREGUNTAS_SUCCESS = 'FETCH_PREGUNTAS_SUCCESS';
export const FETCH_PREGUNTAS_FAILED = 'FETCH_PREGUNTAS_FAILED';

export const CREATE_RESPUESTA_REQUEST = 'CREATE_RESPUESTA_REQUEST';
export const CREATE_RESPUESTA_SUCCESS = 'CREATE_RESPUESTA_SUCCESS';
export const CREATE_RESPUESTA_FAILED = 'CREATE_RESPUESTA_FAILED';

export const FETCH_SUCURSALES_REQUEST = 'FETCH_SUCURSALES_REQUEST';
export const FETCH_SUCURSALES_SUCCESS = 'FETCH_SUCURSALES_SUCCESS';
export const FETCH_SUCURSALES_FAILED = 'FETCH_SUCURSALES_FAILED';
export const FETCH_SUCURSAL_REQUEST = 'FETCH_SUCURSAL_REQUEST';
export const FETCH_SUCURSAL_SUCCESS = 'FETCH_SUCURSAL_SUCCESS';
export const FETCH_SUCURSAL_FAILED = 'FETCH_SUCURSAL_FAILED';