export const CREATE_OR_GET_AUDITORIA_REQUEST =
  'CREATE_OR_GET_AUDITORIA_REQUEST';
export const CREATE_OR_GET_AUDITORIA_SUCCESS =
  'CREATE_OR_GET_AUDITORIA_SUCCESS';
export const CREATE_OR_GET_AUDITORIA_FAILED = 'CREATE_OR_GET_AUDITORIA_FAILED';
export const CREATE_OR_GET_AUDITORIA_RESET = 'CREATE_OR_GET_AUDITORIA_RESET';

export const FETCH_PREGUNTAS_REQUEST = 'FETCH_PREGUNTAS_REQUEST';
export const FETCH_PREGUNTAS_SUCCESS = 'FETCH_PREGUNTAS_SUCCESS';
export const FETCH_PREGUNTAS_FAILED = 'FETCH_PREGUNTAS_FAILED';

export const ADD_RESPUESTA = 'ADD_RESPUESTA';
export const ADD_RESPUESTA_FIELD = 'ADD_RESPUESTA_FIELD';
export const RESPUESTAS_RESET = 'RESPUESTAS_RESET';
export const FETCH_RESPUESTAS_REQUEST = 'FETCH_RESPUESTAS_REQUEST';
export const FETCH_RESPUESTAS_SUCCESS = 'FETCH_RESPUESTAS_SUCCESS';
export const FETCH_RESPUESTAS_FAILED = 'FETCH_RESPUESTAS_FAILED';
export const SEND_RESPUESTAS_REQUEST = 'SEND_RESPUESTAS_REQUEST';
export const SEND_RESPUESTAS_SUCCESS = 'SEND_RESPUESTAS_SUCCESS';
export const SEND_RESPUESTAS_FAILED = 'SEND_RESPUESTAS_FAILED';

export const FETCH_SUCURSALES_REQUEST = 'FETCH_SUCURSALES_REQUEST';
export const FETCH_SUCURSALES_SUCCESS = 'FETCH_SUCURSALES_SUCCESS';
export const FETCH_SUCURSALES_FAILED = 'FETCH_SUCURSALES_FAILED';
export const FETCH_SUCURSAL_REQUEST = 'FETCH_SUCURSAL_REQUEST';
export const FETCH_SUCURSAL_SUCCESS = 'FETCH_SUCURSAL_SUCCESS';
export const FETCH_SUCURSAL_FAILED = 'FETCH_SUCURSAL_FAILED';
export const FETCH_SUCURSAL_RESET = 'FETCH_SUCURSAL_RESET';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
