# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [pull_request]

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      run: docker-compose build
    - name: Docker Run (in background)
      run: docker-compose up -d
    - name: Run tests
      run: docker exec -i lanthorn-backend_web_1 pytest
    - name: Docker stop (Backend server)
      run: docker stop lanthorn-backend_web_1
    - name: Docker stop (DB)
      run: docker stop lanthorn_db
