# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
      - fix/github-action
  pull_request:
    branches:
      - dev
    paths:
      - "server/**"

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Build
        working-directory: server
        run: docker-compose build
      - name: Docker Run (in background)
        working-directory: server
        run: docker-compose up -d
      - name: Setup app
        working-directory: server
        run: docker exec -i speech-to-text-server python manage.py wait_for_db && python manage.py migrate
      - name: Accessing The Container and Running Tests
        working-directory: server
        run: docker exec -i speech-to-text-server python manage.py test
      - name: Docker stop (Backend server)
        working-directory: server
        run: docker stop speech-to-text-server
      - name: Docker stop (DB)
        working-directory: server
        run: docker stop server_db_1
